### ISSUE TITLE
keep showing the Buttons in error under system tab

### ISSUE THREAD

**Issue by BearsMan** [Friendly0Fire/GW2Addons#55]
https://i.imgur.com/AP9p6jC.jpg
Picture of the systems tab in the middle should it be showing those
-running Windows 10
-GPU = NVIDIA GeForce 940M

**Comment by SubActif** [comment]
Gné ?
This is screen with ArcDPS, not GW2Mounts !
Your version of ArcDPS is out dated (this is why you had error message)

I think the name GW2Addons is not the most appropriate because in fact here it is only GW2Mounts as addons, the others are on other github or site.

ArcDPS : https://www.deltaconnected.com/arcdps/
