### ISSUE TITLE
(Feature) Favorite Mount

### ISSUE THREAD

**Issue by CemuUser8** [Friendly0Fire/GW2Addons#8]
Hello, 
 I am really enjoying using this addon, great work.

I have an idea I think would be cool to have, and that is an option to pick a favorite (maybe a radio button next to each mount you can select) and have that chosen favorite be in the middle. I know that this would then require you to be able to put that `fifth mount` in either of the other locations depending on which is the favorite, or have the favorites original location be blank if the extra mount option isn't enabled. For most who have that `fifth mount` it would probably be their favorite anyways, but since a lot of people don't have it yet, it might be nice.

To mimic this feature currently I've just set the hotkey for the `fifth mount` to be the same as what I'd consider my current favorite.

&nbsp;

Anyway, just a thought, thank you again.

**Comment by Friendly0Fire** [comment]
So I'd like to have the ability to basically reorder the mounts however you like, but the problem is that the art for each mount only works in the current configuration, so in order to support that I'd have to change the art entirely and, well, I'm an absolutely dreadful artist.

If someone can provide me with mount art that can easily be rearranged to fit any of the five locations, I'd be more than happy to make them all customizable.
